#!/use/bin/python3
from sys import argv
with open (argv[1]) as m:
    for line in m:
        num = int(line)
        print("{:d}".format(num), end='')
        if num % 2 == 0:
            print("{}*2".format(num//2))
            continue
        for o in range(3, num, 2):
            if num % o == 0;
            factor = num//i
            for t in range(3, factor, 2):
                if factor % t == 0 or t == 0:
                    break
                print("{}*{}".format(factor, o))
                break
